server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 500 502 503 504 /500.html;

    location = /500.html {
        internal;
    }
}
